MainWindow.xaml.cs
Utilities.cs

Fix some minor issues with the last PR, as reported by users.

Minor fixes

---

Constants.cs
MainWindow.xaml.cs
Utilities.cs

This PR adds the ability to check DIC parameters which will be especially useful for the custom parameters. Even though DIC will just close if it's incorrect, this prevents needing to get to that point and provides a better mechanism.

Enable validation of DIC parameters

---

Constants.cs
MainWindow.xaml
MainWindow.xaml.cs
Utilities.cs

Try to populate the drive speed automatically using DIC. (Fixes #11)

Populate drive speed

---

App.config
MainWindow.xaml
MainWindow.xaml.cs

Add more changes for minor issues and UI reactivity.
Added the disc eject and secondary dumping parts for Saturn.
Fixes #20 Fixes #17

More fixes

---

DICUI.csproj
DumpInformation.cs
MainWindow.xaml.cs
Utilities.cs

Minor fixes to some code and the button handling in the Settings window.
Added full, in-GUI support for floppy dumping (fixes #12).

Fixes and Floppies

---

MainWindow.xaml
MainWindow.xaml.cs
Utilities.cs

This updates parameter checking to allow for fully custom commandlines to be validated and an (attempted) match of output submission info will be created with it. This also cleans up a lot of the horrid duplicate code that was there before.

Parameter Checking updates

---

MainWindow.xaml.cs
Utilities/DumpInformation.cs
Utilities/Validation.cs

Add specialty field checking for PS1, PS2, and Saturn.
Fixes some minor issues as well.

Add specialty checking for PS1, PS2, and Saturn

---

App.config
MainWindow.xaml.cs
Options.cs
OptionsWindow.xaml
OptionsWindow.xaml.cs

Remove all references to sg-raw since DIC now outputs the proper PIC.bin file. Fixes #60.

Remove sg-raw

---

DICUI.csproj
Data/Constants.cs
Data/Enumerations.cs
MainWindow.xaml.cs
Utilities/Converters.cs
Utilities/DumpInformation.cs
Utilities/Validation.cs
Utilities/Validators.cs

This PR is a combination cleanup and feature update, including some WIP items that are not hooked up.
Starts the framework for the following:
- Checking drive speed without the need for DIC (#69)
- There are a couple different prototypes for this currently, there's no guarantee that either of them will be the ultimate solution
- Report if a disc is XDG3 (#71) - this is by virtue of the next item
Adds the following abilities:
- Detecting disc type automatically (fixes #49) - this is not 100% complete as DVD-based discs will show up as DVD only (XBOX/360 discs especially)

Usability Updates

---

DICUI.Test/Utilities/DumpEnvironmentTest.cs
DICUI.Test/Utilities/ParametersTest.cs
DICUI/Utilities/Parameters.cs
README.md
appveyor.yml

This creates an automatic AppVeyor run for stuff and fixes failing tests.

AppVeyor and Test

---

README.md

Adding myself to the commit history if I wasn't already in it :P

Fix README formatting in "Notable Testers" Section

---

MPF/ViewModels/LogViewModel.cs
MPF/Windows/MainWindow.xaml

Fixes an issue with Windows 7 where the Help menu item was not visible.

Windows 7 UI Fix

---

MPF.Core/Data/Drive.cs

Fixed console return typo

---

MPF.Modules/Aaru/Parameters.cs
MPF.Modules/BaseParameters.cs
MPF.Modules/DD/Parameters.cs
MPF.Modules/DiscImageCreator/Parameters.cs
MPF.Modules/Redumper/Parameters.cs

I haven't compiled or tested this. I followed the pattern for parsing the version.
If it works, it should resolve https://github.com/SabreTools/MPF/issues/420.

Populate internal serial from PS4 disc

---

MPF.Modules/Aaru/Parameters.cs
MPF.Modules/BaseParameters.cs
MPF.Modules/DD/Parameters.cs
MPF.Modules/DiscImageCreator/Parameters.cs
MPF.Modules/Redumper/Parameters.cs

Similar to the extraction of version from param.json

Populate internal serial from PS5 disc

---

MPF.Core/Converters/EnumConverter.cs
MPF.Modules/Redumper/Parameters.cs

```
Dumping Info:
Dumping Program: redumper v2022.10.28
```
```
Dumping Info:
Dumping Program: redumper v2022.12.22 build_87
```
```
Dumping Info:
Dumping Program: redumper Unknown Version
```

Get the version of redumper

---

MPF.Modules/Redumper/Parameters.cs

```shell
Manufacturer: PLEXTOR
Model: DVDR PX-760A
Firmware: 1.07 (08/18/07 15:10)
```
```shell
Manufacturer: ASUS
Model: BW-16D1HT
Firmware: 3.02 (W000800KLGK8LF2132)
```
```shell
Manufacturer: TSSTcorp
Model: DVD-ROM TS-H352C
Firmware: DE02
```
```shell
Manufacturer: PLEXTOR
Model: CD-R PREMIUM2
Firmware: <empty>
```

Pull hardware info from redumper log

---

MPF.Library/Protection.cs

Updates sanitization for SafeDisc for latest BOS outputs.

Update SafeDisc Sanitization

---

MPF.Modules/Aaru/Parameters.cs
MPF.Modules/CleanRIp/Parameters.cs
MPF.Modules/DiscImageCreator/Parameters.cs
MPF.Modules/Redumper/Parameters.cs
MPF.Modules/UmdImageCreator/Parameters.cs
MPF.Test/RedumpLib/SubmissionInfoTests.cs
MPF/ViewModels/MainViewModel.cs

Timestamp used 12-hour clock. Fixed to 24-hour.

Fix timestamp

---

MPF.Core/Modules/DiscImageCreator/Parameters.cs

The condition seems to be reversed.

Fix GetPVD in dic

---

CHANGELIST.md
MPF.Core/Modules/DiscImageCreator/Parameters.cs
MPF.Core/Modules/Redumper/Parameters.cs
MPF.Core/SubmissionInfoTool.cs

* Output ringcode information of layer 2 and 3 to !submissionInfo.txt
* Increase PIC length
```
Layer 0 (Outer) Mastering Code (laser branded/etched): (REQUIRED, IF EXISTS)
Layer 0 (Outer) Mastering SID Code: (REQUIRED, IF EXISTS)
Layer 0 (Outer) Toolstamp or Mastering Code (engraved/stamped): (REQUIRED, IF EXISTS)
Data Side Mould SID Code: (REQUIRED, IF EXISTS)
Data Side Additional Mould: (REQUIRED, IF EXISTS)
Layer 1 Mastering Code (laser branded/etched): (REQUIRED, IF EXISTS)
Layer 1 Mastering SID Code: (REQUIRED, IF EXISTS)
Layer 1 Toolstamp or Mastering Code (engraved/stamped): (REQUIRED, IF EXISTS)
Label Side Mould SID Code: (REQUIRED, IF EXISTS)
Layer 2 (Inner) Mastering Code (laser branded/etched): (REQUIRED, IF EXISTS)
Layer 2 (Inner) Mastering SID Code: (REQUIRED, IF EXISTS) …
```

Support ringcode and PIC for triple/quad-layer 

---

CHANGELIST.md
MPF.Core/Modules/Redumper/Constants.cs
MPF.Core/Modules/Redumper/Parameters.cs
appveyor.yml

Commands added: Rings, Dumpnew, Refinenew (Dumpnew and Refinenew are temporary, as they are WIP)
Flags added: Version, DumpWriteOffset, LegacySubs, DisableCDText
Flags renamed: PlextorLeadinSkip -> PlextorSkipLeadin

Update Redumper to build 311

---

CHANGELIST.md
MPF.Core/Data/Drive.cs

Detects CDTV with the presence of either CDTV.TM or S/STARTUP-SEQUENCE
Fixes #629

Detect CDTV discs

---

CHANGELIST.md
MPF.Core/MPF.Core.csproj
MPF.Core/UI/ViewModels/CreateIRDViewModel.cs
MPF.UI.Core/Windows/CreateIRDWindow.xaml
MPF.UI.Core/Windows/CreateIRDWindow.xaml.cs

- Updates LibIRD to v0.6.0 which is much faster for slow reads (HDDs, network shares, etc)
- Disables the UI elements on the Create IRD window when the IRD is being created

Update LibIRD, disable UI elements when creating IRD

---

CHANGELIST.md
MPF.Core/InfoTool.cs

Better logic
More punctuation cases may be needed?
Fixes #667

Fix title normalization

---

CHANGELIST.md
MPF.Core/UI/ViewModels/CheckDumpViewModel.cs
MPF.UI.Core/Windows/CheckDumpWindow.xaml
MPF.UI.Core/Windows/CheckDumpWindow.xaml.cs

No longer hangs when performing async tasks in Check UI
net40 is still broken, which is not a change in functionality

Fix Check UI deadlock

---

CHANGELIST.md
MPF.Core/Modules/Redumper/Parameters.cs

Need full caps GENERIC drive type for Redumper
Fixes #676

Fix Redumper generic drive type

---

CHANGELIST.md
MPF.Core/SubmissionInfoTool.cs

Half of #666 
I haven't tested this at all

Add MPF version to Submission info

---

CHANGELIST.md
MPF.Core/Modules/Redumper/Parameters.cs

Fix information pulling for redumper

---

CHANGELIST.md
MPF.Core/Data/Drive.cs

Detect Xbox Series X discs via catalog.js serialization
Fixes #675

Detect Xbox Series X discs

---

CHANGELIST.md
MPF.Frontend/ViewModels/MainViewModel.cs

Don't set MediaType if parameters ambiguous

---

MPF.Check/Program.cs

Enable loading seed JSON

---

CHANGELIST.md
MPF.Processors/ProcessingTool.cs

XGD3 Layer1 SS range is currently wrong, this fixes it

Fix XGD3 SS ranges

---

CHANGELIST.md
MPF.Processors/ProcessingTool.cs

Invert SSv2 logic to fix cleaning XGD3 SS

Fix cleaning XGD3 SS

---

CHANGELIST.md
MPF.Frontend/ViewModels/MainViewModel.cs
MPF.UI/Windows/OptionsWindow.xaml

%SYS% now defaults to uppercase (i.e. /DVD-VIDEO/), unless you specify %sys%
The tooltip also works on the label in the options now.

Improve parameters for default output path

---

CHANGELIST.md
MPF.Frontend/Tools/FrontendTool.cs
MPF.Frontend/Tools/SubmissionGenerator.cs
MPF.Processors/DiscImageCreator.cs

Trying to do a minimal effort solution to #744
No testing done yet.
Also removed Joliet parsing for DIC, it seems to be broken at the moment.

Better deal with volume labels

---

CHANGELIST.md
MPF.Processors.Test/RedumperTests.cs
MPF.Processors/DiscImageCreator.cs
MPF.Processors/Enumerations.cs
MPF.Processors/Redumper.cs

Adds warning to comments if SecuROM sector count is not expected.
Fixes #752

Verify SecuROM sector count

---

CHANGELIST.md
MPF.UI/UserControls/LogOutput.xaml

Pedantic GUI changes

---

CHANGELIST.md
MPF.UI/Windows/CheckDumpWindow.xaml
MPF.UI/Windows/CreateIRDWindow.xaml
MPF.UI/Windows/OptionsWindow.xaml

Fixes padding and gaps in groupboxes

More pendantic GUI changes

---

CHANGELIST.md
MPF.Frontend/DumpEnvironment.cs
MPF.Frontend/ViewModels/MainViewModel.cs
MPF.Processors.Test/AaruTests.cs
MPF.Processors.Test/CleanRipTests.cs
MPF.Processors.Test/DiscImageCreatorTests.cs
MPF.Processors.Test/PS3CFWTests.cs
MPF.Processors.Test/RedumperTests.cs
MPF.Processors.Test/UmdImageCreatorTests.cs
MPF.Processors.Test/XboxBackupCreatorTests.cs
MPF.Processors/BaseProcessor.cs

Extends pre-dump validates to check for partial dumps.

Check for partial dumps

---

CHANGELIST.md
MPF.Processors/CleanRip.cs
MPF.Processors/DiscImageCreator.cs
MPF.Processors/Redumper.cs
MPF.Processors/XboxBackupCreator.cs

- XGD region behind redumpCompat
- Gamecube/Wii Version and Region behind redumpCompat

More fields behind RedumpCompatible option

---

CHANGELIST.md
MPF.Processors.Test/RedumperTests.cs
MPF.Processors.Test/TestData/Redumper/CDROM/test.log
MPF.Processors/Redumper.cs

Parses PS2 protection info from redumper log
Fixes #796

Parse redumper BIG.DAT info

---

CHANGELIST.md
MPF.Frontend/Tools/PhysicalTool.cs

- Also print the version hash
- Filesize checks to prevent read errors
- Reformat info printing

Improve PS4/PS5 parsing

---

MPF.UI/Windows/DiscInformationWindow.xaml.cs

Resolves https://github.com/SabreTools/MPF/issues/825

Fix typo for L1Toolstamp!.Label

---

CHANGELIST.md
MPF.UI/Windows/OptionsWindow.xaml

Adds "0" in options for each disc type.
As requested by @Ragowit

Allow max speed dumping

---

CHANGELIST.md
MPF.Processors/BaseProcessor.cs
MPF.Processors/Redumper.cs

Better audio-only check

---

CHANGELIST.md
MPF.Processors/Redumper.cs

This PR resolves the issue where C2 errors were doubling in the Dumping Info section.
```
Dumping Info:
Frontend Version: 3.3.3-0685972842b7bc58e086cdf9ae007d1b80614ec5
Dumping Program: Redumper v2025.07.14 build_631
Date: 2025-08-03 10:52:15
Parameters: disc --verbose --skeleton --drive=g: --speed=24 --retries=20 --image-name=dump
Manufacturer: PLEXTOR
Model: DVDR PX-760A
Firmware: 1.07 (08/18/07 15:10)
Reported Disc Type: CD-ROM
C2 Error Count: 1712
```
```
Dumping Info:
Frontend Version: 3.3.3
Dumping Program: Redumper v2025.07.14 build_631
Date: 2025-08-03 10:52:15
Parameters: disc --verbose --skeleton --drive=g: --speed=24 --retries=20 --image-name=dump
Manufacturer: PLEXTOR
Model: DVDR PX-760A
Firmware: 1.07 (08/18/07 15:10)
Reported Disc Type: CD-ROM
C2 Error Count: 856
``` …

Fix for C2 error doubling issue

---

CHANGELIST.md
MPF.Processors/Redumper.cs

This PR updates the code to handle redumper's new version format.

Support new versioning format in redumper
