SabreTools/MPF

- MainWindow.xaml.cs
Fixed a few issues I found:
1. PC CD (no copy protection) had type set to dvd
2. Output path wasn't quoted when running DiscImageCreator
3. PSX.bat was missing backslashes after output directory
> Fix a few issues

- DICUI.csproj
- MainWindow.xaml
- MainWindow.xaml.cs
This change adds all remaining consoles and disc-based devices that are currently listed in Redump as valid devices. This also does some minor renames and splits that bring this to parity as well. One minor TODO note was added possibly for future ease-of-use for dumping IBM PC software.
The second commit disables application signing because no certificate is in the repository and nobody but the original author would be able to build this from source otherwise.
> Bring list to parity with Redump known types

- MainWindow.xaml
- MainWindow.xaml.cs
This commit consolidates the 4 IBM PC-CD variants into a single option. This will reduce the amount of confusion to new users in the future since they will be able to dump any CD right off the bat. The other commits dealt with merge issues I had due to not syncing branches before making my changes. I believe I also added "bd" as the type for BD-Video and changed the Audio CD type to "cd", since the "audio" command is more fiddly than it seems.
> Combine IBM PC-CD options, misc fixes

- App.config
- MainWindow.xaml
- MainWindow.xaml.cs
- Properties/Settings.Designer.cs
- Properties/Settings.settings
This change converts the static DIC path to one that is controlled by settings. Currently, nothing saves or changes these settings so nothing has changed in terms of what the workflow is. This will, however, enable these settings to be controlled through the UI in the future, and allow for settings persistence between sessions without having to rely on AppData or the registry.
>  Enable future settings use

- DICUI.csproj
- Enumerations.cs
- MainWindow.xaml
- MainWindow.xaml.cs
- Utilities.cs
This PR adds enumerations, helper methods, and combobox automation to make the system more extensible in the future. This includes things like automatically getting the list of items in the box, setting default parameters better, and even filling in some previously-missing formats.
I encourage local testing to make sure that all items are still working as intended.
My merge with the main branch (Merge branch 'master') removes the unnecessary additional ECC check for CDs. If the EccEdc executable is in the folder with DIC, it will automatically run and create the required _eccEdc.txt file. I was trying to mention this in #21 but to no avail.
> Add Enumerations; Helper Methods

- MainWindow.xaml.cs
- Utilities.cs
Provide a basic framework for getting all required disc information in one place.
Currently, this is not practically hooked up (just a Dictionary is populated), but in a future PR, this will result in an outputted file with all of the information correctly formatted.
Known issues with this commit:
- Not all error counts (and warning counts) are correctly detected
- Missing values are not handled gracefully (usually just set to null)
- The Utilities class is starting to get bloated with too much disparate stuff
> Disc Information Framework

- Constants.cs
- DICUI.csproj
- MainWindow.xaml.cs
- Utilities.cs
First round of outputting all required disc information to file for easy submission.
Currently fully supports:
- Apple Macintosh (CD/DVD)
- IBM PC Compatibles (CD/DVD)
- Sega Saturn (CD, some values are not automatically generated)
- Sony PlayStation (CD, some values are not automatically generated)
- Sony PlayStation 2 (CD/DVD, some values are not automatically generated)
- Generic CD, DVD, BD (only default information, no system-specific ones)
Current known issues:
- PSX libcrypt, EDC, and Anti-modchip are not filled in automatically
- PSX/PS2 EXE dates are not filled in automatically
- Saturn header and build date are not filled in automatically
- Not all system-specific values are supported
Addresses #9, #23
> Write Centralized Disc Information

- MainWindow.xaml
- MainWindow.xaml.cs
- Utilities.cs
Addresses #14.
This change makes it so that the current commandline params are displayed in a disabled text box but when the custom option is selected, the other parts get disabled and you have full control over the commandline. This can allow any customization that users would like. It also simplifies the code that gets called when the DiscImageCreator instance gets run.
The changes to the xaml are incidental, they're just reordering (sans the addition of the new grid row for the custom parameters).
> Add Custom Parameter Support

- MainWindow.xaml.cs
Add verification dialog in case the user is overwriting a complete existing dump. This is ONLY for a complete existing dump, so users who ran into an error won't be pestered every time.
Addresses #30
> Add verification for overwrite

- Constants.cs
- MainWindow.xaml
- MainWindow.xaml.cs
This change allows a child process to be killed in the middle of it running. Beware, this can cause issues with the output files if used incorrectly.
> Allow child process to be killed (#10)

- App.config
- Constants.cs
- MainWindow.xaml.cs
- Utilities.cs
This adds the automatic addition of the SecuROM data (from _subIntention.txt) into the output, only if the file is not empty. Otherwise, it is seen as unneeded and isn't even mentioned in the output.
> Add SubIntention (SecuROM) field

- Constants.cs
- Enumerations.cs
- MainWindow.xaml.cs
- Utilities/Converters.cs
- Utilities/DumpInformation.cs
- Utilities/Validation.cs
This PR addresses the following:
- Fixes #52 - This needs testing, but I have combined the single- and dual-layer disc types into a single enum value each. This is achieved by checking for the presence of the layerbreak field in the output data. At the moment, this means that it is entirely transparent to the user what type of disc this is. Followup item (possibly for this PR): Output the disc type to either the name of the file OR a field within the submission info file.
- Fixes #53 - A few more undumpable formats have been added to the internal list along with the migration of HD-DVD out of the valid formats for X360 (XDG2/3). This should address any semantic issues as well as allow for some fairly interesting cases later when more options arise besides DIC to backup media.
- Cleanup …
> Formats and Types

- Constants.cs
- MainWindow.xaml.cs
- Utilities/DumpInformation.cs
- Utilities/Validation.cs
Add the system and media type to the output submission info. This also entails putting the proper postfix on the DVD and BD outputs to denote which type it should be submitted as in the New Disc form. Fixes #62
> Add system and media type to output submission info

- CHANGELIST.md
- Constants.cs
- DICUI.csproj
- Enumerations.cs
- External/IOrderedDictionary.cs
- External/OrderedDictionary.cs
- MainWindow.xaml
- MainWindow.xaml.cs
- Options.cs
- README.md
- Utilities/Converters.cs
- Utilities/DumpInformation.cs
- Utilities/Validation.cs
- Renamed `DiscType` to `MediaType` to better reflect the enum values (fixes #67)
- Created CHANGELIST.md for a better, centralized experience (edited README.md in the process) (fixes #68)
- Remove as many usages of tuple as possible for the time being (fixes #66)
- Added the `OrderedDictionary<TKey, TValue>` type for future use. This is a generic version of the `System.Collections.Specialized.OrderedDictionary` type
- Add string replacement for both `.` and `&` until a better solution can be found (fixes #54) (fixes #59)
- As of now, both characters are replaced by `_`. This can be changed in the future.
> Bits and Pieces

- App.config
- Data/Constants.cs
- MainWindow.xaml.cs
- Options.cs
- OptionsWindow.xaml
- OptionsWindow.xaml.cs
- Utilities/Converters.cs
- Utilities/DumpInformation.cs
- appveyor.yml
The current code can have >=3 calls to some functions in a row due to a misunderstanding on how the setting of an index triggers the change events. This PR should remove the worst offenders for duplicate calls, presumably making startup and some item changes a lot smoother.
For the PSX automation, there are the following changes:
- EDC check becomes automatic, due to similarities in how the error count and EDC are checked
- Anti-modchip string check becomes automatic thanks to the `/am` flag (Thanks to TonyLizard for helping find this)
- LibCrypt check becomes automatic thanks to the `/nl` flag and the existence of the `_subIntention.txt` file, similar to SecuROM for PC discs (Thanks to TonyLizard for helping find this)
Because of that last item, psxt001z is no longer needed, and has been …
> Remove Redundant Calls and PSX Automation

- Data/Constants.cs
- MainWindow.xaml.cs
- Utilities/Converters.cs
- Utilities/Validators.cs
This PR does three major things:
- Strips out a lot of redundant calls (due to callbacks firing) as well as reducing the amount of separate helper methods (by one, but it counts)
- Makes the currently detected / selected media type "stickier" so that it persists more properly across changing systems. This also has the ability of showing the "detected disc was X but system does not support it" message in more relevant cases now.
- Makes HD-DVD a first-class citizen, since apparently DiscImageCreator can dump it using the `dvd` command
On the side, this also adds more prototype code and notes for removing DIC as the way to get drive speeds.
> Streamline Callbacks and Ensure MediaType

- DICUI/Utilities/DumpEnvironment.cs
This PR removes the "disable beep" flag from the Eject and Get Drive Speed calls to DIC, since it's not supported for those. This was found from seeing a couple dozen instances of DiscImageCreator sitting in Task Manager after testing. This also makes the drive speed finding more robust so that it tries to fail fast.
> Remove Disable Beep; Handle Error Case

- DICUI/DICUI.csproj
- DICUI/Data/Enumerations.cs
- DICUI/MainWindow.xaml.cs
- DICUI/Utilities/Converters.cs
- DICUI/Utilities/DumpEnvironment.cs
- DICUI/Utilities/Validators.cs
- DICUI/packages.config
This PR has two major items:
- Update external packages (BurnOutSharp and Unshield)
- Make it so that external tools and submission info creation don't block the main thread
This PR also includes a couple of minor things:
- Added "Rainbow Disc" as a valid output option for the whole, like, 1 disc that falls in that category
- Added more formats to the same output fields as IBM and Macintosh
- Fixed automatic filling of output paths (this one was somehow really broken the old way, often reverting to just "disc". No idea why, but the cleaner code has not run into this issue)
> Unblock and Update

- DICUI/OptionsWindow.xaml
- DICUI/Utilities/DumpEnvironment.cs
On two strings in DICUI, DIC was mispelled _(Disk_ instead of _Disc_ that DIC uses) in the Log and Options windows. This small PR should fix that.
It's mainly just for consistency of the strings in the end.
> Change printable string misspellings relating to DIC 

- DICUI.Library/Data/Constants.cs
- DICUI.Library/Data/Enumerations.cs
- DICUI.Library/Utilities/ChefParameters.cs
- DICUI.Library/Utilities/Converters.cs
- DICUI.Library/Utilities/CreatorParameters.cs
- DICUI.Library/Utilities/DumpEnvironment.cs
- DICUI.Library/Utilities/Extensions.cs
- DICUI.Test/Utilities/ConvertersTest.cs
- DICUI.Test/Utilities/MediaTypeExtensionsTest.cs
- DICUI/App.config
- DICUI/EnumDescriptionConverter.cs
- DICUI/Options.cs
- DICUI/ViewModels.cs
- DICUI/Windows/MainWindow.xaml
- DICUI/Windows/MainWindow.xaml.cs
- DICUI/Windows/OptionsWindow.xaml
- DICUI/Windows/OptionsWindow.xaml.cs
- README.md
- appveyor.yml
This PR is a massive amount of work to support DiscImageChef to the same base level as DiscImageCreator. Here is a list of things that it does and does not do:
- Adds paths, command, and flag validation specific to DiscImageChef
- Add nearly all constants and enumerations required for current and future work
- Update other parts of code with improvements from the DiscImageChef parameter work
- Add non-UI setting for enabling DiscImageChef dumping
- **NO** submission info generation or output file parsing
- **NO** split file outputs to correspond to DiscImageCreator compatibility
- Edited default paths for both DiscImageCreator and Subdump to reflect the possibility of more supported programs in the future
- Updated DiscImageCreator version for automated builds
- **NO** automatic building …
> Preliminary Support for DiscImageChef

- CHANGELIST.md
- MPF.Check/Program.cs
- MPF.Library/Aaru/Parameters.cs
- MPF.Library/CleanRIp/Parameters.cs
- MPF.Library/DD/Parameters.cs
- MPF.Library/Data/BaseParameters.cs
- MPF.Library/Data/DumpEnvironment.cs
- MPF.Library/Data/Options.cs
- MPF.Library/DiscImageCreator/Parameters.cs
- MPF.Library/MPF.Library.csproj
- MPF.Library/UmdImageCreator/Parameters.cs
- MPF/Windows/OptionsWindow.xaml
This has been a long-requested feature that we finally have room in the options menu to support. This new option allows for all files considered "log files" to be compressed into a zip file after dumping, deleting the uncompressed versions. This helps save on space and helps with submissions. This option currently defaults to disabled.
Both Aaru and DiscImageCreator currently support this, as they're the only ones that have log files and dumping support combined. This has been tested to ensure that all log files (including the dreaded new command file in DIC) are archived. **Edit:** As of one of the more recent commits, Check support has been added so compression can be applied after the fact. This also means that both CleanRip and UmdImageCreator both can have their logs compressed as …
> Add option to compress log files after dumping

- MPF.Library/Data/ProcessingQueue.cs
When doing nothing, MPF maxes out a CPU core due to a loop. This wasnt in 1.18, so its fairly recent addition. I have just added a small sleep, but you may want to do it another way.
Either way, fix stops the loop maxing out a core.
> Fix for high cpu usage, issue with loop.

- MPF/App.xaml
- MPF/MPF.csproj
Just had to "downgrade" the Aero reference and it now launches and runs just fine in Windows 7.
> Fixed launching MPF in Windows 7.

- MPF/ViewModels/MainViewModel.cs
- MPF/Windows/MainWindow.xaml
Behaves identically to switching the selected drive combo box. (Calls the InitializeUIValues method with rescanDrives set to false.)
Perhaps it might be better if this button assumed no auto-scan and just updates the label always skipping SystemType detection?
> Added a button to quickly update the volume label and dump path.

- MPF.Core/Data/Drive.cs
Adds PS4 detection based on the existence of `PS4/UPDATE/PS4UPDATE.PUP`, and also added some comments about other files that can be found on PS4 discs.
> Add PS4 detection for discs that do not use `PS4VOLUME` label

- MPF.Library/InfoTool.cs
Suppresses excessive "+".
I don't know C#, please modify accordingly.
```c#
string[] offsets = new string[] { "-1", "0", "1", "+1", "", "abc", null };
// current
foreach (string o in offsets) {
string offset = o;
if (offset?.StartsWith("-") == false)
offset = $"+{offset}";
System.Console.Write("[" + offset + "] ");
}
//=> [-1] [+0] [+1] [++1] [+] [+abc] [] 
System.Console.WriteLine();
// this PR
foreach (string o in offsets) {
string offset = o;
if (Int32.TryParse(offset, out int i))
offset = i.ToString("+#;-#;0");
System.Console.Write("[" + offset + "] ");
}
//=> [-1] [0] [+1] [+1] [] [abc] [] 
```
> Add + to positive offsets in a better way

- CHANGELIST.md
- MPF.Check/MPF.Check.csproj
- MPF.Check/Program.cs
- MPF.Core/MPF.Core.csproj
- MPF.Library/DumpEnvironment.cs
- MPF.Library/InfoTool.cs
- MPF.Library/MPF.Library.csproj
- MPF.Modules/BaseParameters.cs
- MPF.Test/Library/DumpEnvironmentTests.cs
- MPF.Test/Library/InfoToolTests.cs
- MPF.Test/MPF.Test.csproj
- MPF.UI.Core/MPF.UI.Core.csproj
- MPF/MPF.csproj
- MPF/ViewModels/MainViewModel.cs
- MPF/Windows/MainWindow.xaml
This PR does the following:
- Updates Nuget packages to newest version
- Combines output directory and filename into an output path box (fixes https://github.com/SabreTools/MPF/issues/431)
- Cleanup internal normalization, including replacing `.` with `_` for DIC, again (fixes https://github.com/SabreTools/MPF/issues/437)
- Force drive update before dump to ensure volume label is set (fixes https://github.com/SabreTools/MPF/issues/430)
- Show a popup box if you have empty parameters when trying to dump
> General UI Cleanup

- MPF.Modules/Redumper/Parameters.cs
Skip all lines in the detection.
```
detecting offset
audio silence detection... done
Perfect Audio Offset (silence level: 0): [-28707 .. +15478]
warning: fallback offset 0 applied
disc write offset: +0
detection complete (time: 15s)
```
```
detecting offset
audio silence detection... done
Perfect Audio Offset (silence level: 0): -12
Perfect Audio Offset applied
disc write offset: -12
detection complete (time: 17s)
```
```
detecting offset
data track detected
disc write offset: -12
detection complete (time: 0s)
```
> Improve write offset detection for redumper

- MPF/Windows/OptionsWindow.xaml
Made "Output Protection File" to be consistent with "Output Submission JSON".
> Make output file options consistent

- MPF.Core/Data/Options.cs
- MPF/ViewModels/MainViewModel.cs
- MPF/Windows/OptionsWindow.xaml
Sets up the environment and simply updates the output path and filename. No System, Media, Drive, or Speed changes. It's a very fast update meant for large lots of similar discs.
> Originally intended behaviour of the Update Label button.

- MPF.Modules/Redumper/Parameters.cs
I have simplified the process so it may not work correctly in the situation the original code envisioned.
It also does not process previous logs.
```
data errors [dump.bin]:
ECC: 10
EDC: 10
redump: 10
```
```
*** MODE: info
CD-ROM [dump.bin]:
sectors count: 271236
mode1 sectors: 271236
ECC errors: 65
EDC errors: 65
REDUMP.ORG errors: 65
```
> Get error count from recent redumper log

- MPF.Modules/Redumper/Parameters.cs
The current code does not detect EOF during the search for `REDUMP.ORG errors`.
> Detect EOF during the search for error counts

- MPF.Modules/Redumper/Parameters.cs
`detecting offset` is gone from build 114.
This fix also works for previous redumper (up to build 113).
> Get the write offset from the latest redumper

- MPF.Modules/Redumper/Parameters.cs
Remove fast forwarding because `**** MODE: split` has gone away.
> Get write offset from redumper 119

- MPF.Modules/Redumper/Parameters.cs
Change the current fast-forward keyword as it has become unstable.
I checked with build 151 and 152.
> Update hardware information pull from redumper

- MPF.Modules/BaseParameters.cs
I tested the changes from #542 and they don't work as intended, a "SLPM-645xx" disc is registered as "Japan"
I believe it is because the serial string being passed to this function has a "-" in it, i.e. serial = "SLPM-64511", whereas I had initially assumed it would be "SLPM64511".
Unfortunately I do not have the time to build MPF with this minor change to test this, so unless @mnadareski knows the string format of the serial being passed to this function, then this is the best I can do.
Otherwise, if it still doesn't work this function be simplified again to remove the serial-number parsing.
> Fix serial parsing from #542

- .vscode/tasks.json
- CHANGELIST.md
- MPF.Core/Converters/EnumConverter.cs
- MPF.Core/Data/Drive.cs
- MPF.Core/MPF.Core.csproj
- MPF.Test/Core/Converters/EnumConverterTests.cs
- MPF.Test/MPF.Test.csproj
- MPF.UI.Core/ViewModels/MainViewModel.cs
- MPF.UI.Core/Windows/OptionsWindow.xaml.cs
- README.md
- appveyor.yml
- publish-win.bat
IMAPI2 is a Windows library that allows for media type detection and media burning in Windows applications. It is lightly maintained but is entirely locked to the Windows platform. IMAPI2 is a major blocker to making the entirety of MPF cross-platform, with the other major blocker being the UI framework. Removing this library would mean the end of very accurate media type detection.
Remove IMAPI2 from the application even if it means less accurate media type detection until another solution is found. This solution allows .NET Framework 4.8 builds to be built and packaged near-identically to the newer .NET 6 and .NET 7 builds and places those more modern .NET builds on equal footing.
This is deliberately being made into a separate branch because this is a very divisive change. This removes …
> Remove IMAPI2 as a dependency

- appveyor.yml
- publish-nix.sh
- publish-win.bat
- Explicitly define debug profile in debug builds (For clarity, as Release profile becomes default in .NET 8)
- No debug symbols for release builds in appveyor build
- No debug symbols for release builds in win build script
- No debug symobls for release builds in nix build script
I've checked that it works on my appveyor build, but I havent tested the win/nix scripts so do check my changes :)
> Remove debug symbols in release builds

- README.md
I have built MPF using the build instructions and have some minor fixes to the readme to make
* Mention the publish-win.bat/publish-nix.sh scripts and expand on their requirements.
* Remove 32bit from system requirements
* Add self-contained to build commands to remove warning, as runtime is defined
* Add a missing `|` in the MPF.Check build command
* Add a missing comma
> Clarify build instructions in README

- MPF.Core/UI/ViewModels/MainViewModel.cs
The media type combo box was not updating on user selection, due to the detected media type being chosen first.
I have solved this by clearing the detected media type variable once it has been used.
If you want to preserve the variable, then you can fix this a cleaner way, however pressing 'Scan for discs' does still revert the combo box to the detected media, so this change does do as expected.
> Fix media combobox not updating

- MPF.Core/UI/ViewModels/MainViewModel.cs
Naive solution to #514 
~~Does a check for HDDVD+Redumper every time.
This line can be removed if/when redumper supports HD-DVDs.
Happy to close this if a better solution is worked on.~~
Created helper function that checks whether a given program supports a given media.
Only implemented checks for Redumper + HDDVD or Bluray currently.
> Disable dumping button when Redumper selected with unsupported media type

- MPF.Core/Modules/DiscImageCreator/Parameters.cs
Fixes #506 
- DIC logs for Audio CDs are no longer accepted by redump.org (this change only affects `!submissionInfo.txt` which is mostly used for redump submissions)
- For the universal hash to be accurate, DIC must have the disc write offset manually defined in `/a` flag
- DIC is not being updated in packaged MPF builds
- The currently packaged (and future) builds of DIC do not place the Universal Hash inside *_disc.txt so this code is not currently working correctly
For these reasons, it does not make sense to update or maintain this code, and since the code is now obsolete it should be removed.
> Remove code for getting Universal Hash from DIC logs

- MPF.Core/Data/Drive.cs
Currently, optical media type detection for UDF filesystems is set to DVDs if the size is at least 400MB.
Based on the PC CDs and DVDs in redump, the false positive rate for DVD detection when using a threshold of 800 MB is less than 3%, with an optimal threshold for CD and DVD false detection rate at approx 830MB. However, I think it is best that MPF keep the threshold at 800 MB as CDs greater than 800 MB in size are technically not following the CD-ROM standard.
I have also changed it slightly to set discs with exactly 800 MB as CDs.
Cumulative distributions for PC DVDs (in red) and PC CDs (in blue) with regards to size, where the crossover represents the point with the "lowest false detection rate":
> Set UDF CD threshold at 800MB

- MPF.Core/DumpEnvironment.cs
- MPF.Core/UI/ViewModels/MainViewModel.cs
Set the getFullPath flags to false in the 3 places in MPF that still use full paths (except in MPF.Test).
I have tested this for one disc and had no issues with redumper or DIC, but this probably should be tested with aaru by someone who knows what they're doing.
> Always use relative path internally

- MPF.Test/MPF.Test.csproj
The only `using` for psxt001z inside MPF.Test was deleted but the csproj still has it as a reference.
Note:
It would be nice to put the Libcrypt check from psxt001z into BOS, having the LibCrypt check require its own library doesn't make sense, especially since its only ever used once inside MPF.Core/Protection.cs: https://github.com/SabreTools/MPF/blob/master/MPF.Core/Protection.cs#L142
But I'll leave that to you to decide, I know it's not originally your code.
> Remove psxt001z Pkg Ref in MPF.Test

- MPF.UI.Core/Windows/MainWindow.xaml.cs
Occasionally, the main window hides behind another application after the options window or disc information window is closed.
To replicate current problem:
1. Go to Options
2. Go to the Paths tab, then click on a `...` button so that the windows explorer window pops up
3. Close this window, then close the options window
4. The Main MPF window gets hidden behind previously opened application.
This attempts to solve the problem, but feels like a band-aid solution.
Open to other ideas.
> Focus main window after child window closes

- MPF.Core/InfoTool.cs
- MPF.Core/Modules/Aaru/Parameters.cs
- MPF.Core/Modules/DiscImageCreator/Parameters.cs
- MPF.Core/Modules/Redumper/Parameters.cs
This pulls the PS3 firmware update version (from /PS3_UPDATE/PS3UPDAT.PUP) and puts `PS3 Firmware 1.00` etc in the Patches field.
Implements #597 
Please squash merge :)
> Pull PS3 Firmware Version

- MPF.UI.Core/Windows/OptionsWindow.xaml.cs
The options window currently has a non-functional button to browse for the Redumper executable.
This enables it.
> Enable browsing for Redumper path

- CHANGELIST.md
- MPF.Core/Modules/Redumper/Parameters.cs
Identifies blu-ray PIC for redumper bluray discs.
Is required for small-sized BD-66 discs, to differentiate from BD-50.
Solves #617
> Get BD PIC Identifier for redumper

- CHANGELIST.md
- MPF.Core/MPF.Core.csproj
- MPF.Core/Modules/Redumper/Parameters.cs
- appveyor.yml
- Add .hash/.skeleton files to log zip, for track.iso, track.bin, and multi-track .bin files
- Update SabreTools.Serialization to 1.3.1
Attempts to fix #615
> Support redumper skeleton and hash files

- CHANGELIST.md
- MPF.Core/Data/Options.cs
- MPF.Core/DumpEnvironment.cs
- MPF.Core/InfoTool.cs
- MPF.Core/Utilities/OptionsLoader.cs
- MPF.UI.Core/Windows/OptionsWindow.xaml
- Adds an option to (not by default) remove drive letter from !protectionInfo.txt, Windows only (Fixes #448)
- Sort keys alphabetically, makes !protectionInfo.txt deterministic
> Cleanup !protectionInfo.txt

- CHANGELIST.md
- MPF.Core/Data/Drive.cs
If no volume label is found, and the current system is PSX or PS2, use the PlayStation serial as the volume label instead of "track"
I initially tried for PS3/PS4/PS5 as well, but those systems have a default volume label ("PS3VOLUME" etc), so there is no point doing this for those systems.
Fixes #494
> Use PSX/PS2 serial as filename when Volume Label not present

- MPF.Core/Data/Drive.cs
- MPF.Core/InfoTool.cs
- MPF.Core/UI/ViewModels/MainViewModel.cs
- MPF.UI.Core/Windows/OptionsWindow.xaml
Attempts to provide a general solution/fix for #458 
Type the following keywords into output path or default output path textboxes to use variables:
`%SYSTEM%` = Long name for system
`%SYS%` = Short name for system
`%MEDIA%` = Long name for media type
`%PROGRAM%` = Long name for dumping program
`%PROG%` = Short name for dumping program (currently only DiscImageCreator -> DIC)
`%LABEL%` = Volume Label
`%DATE%` = "YYYYMMDD" current date
`%DATETIME%` = "YYYYMMDD-HHMMSS" current datetime
For now, these are not documented anywhere, but are provided for advanced users.
> Allow variables in output path

- CHANGELIST.md
- MPF.Core/UI/ViewModels/MainViewModel.cs
Checks for presence of a complete dump from other programs before beginning a new dump, to prevent overwriting files.
Fixes #595
> Check for presence of complete dump from other programs

- CHANGELIST.md
- MPF.Core/Data/Drive.cs
- MPF.Core/Modules/BaseParameters.cs
- MPF.Core/Modules/DiscImageCreator/Parameters.cs
- MPF.Core/Modules/Redumper/Parameters.cs
- MPF.Core/SubmissionInfoTool.cs
- Parses ISO label from Redumper logs
- Parses ISO/Joliet/UDF label from DIC logs
- Adds formatted list of labels from logs to [T:VOL] tag, on top of whatever Windows sees
- Adds a `Dictionary<string, List<string>>? VolumeLabels` field to BaseParameters
- Makes `Drive.GetRedumpSystemFromVolumeLabel` a static method 
Attempts to fix #579 
Perhaps needs more testing, and figuring out where in Aaru logs the volume label is.
Note: With this change, Aaru still outputs "[T:VOL] %label%" exactly as prior functionality.
> Retrieve volume label from logs

- CHANGELIST.md
- MPF.Core/Modules/Redumper/Parameters.cs
In rare cases, if there is a space at the end of each line in the PVD output, it will be missing.
Therefore, remove Trim.
> Correct missing space in PVD

- CHANGELIST.md
- MPF.Core/Modules/BaseParameters.cs
Replaces a bunch of .Parse() with .TryParse() 
Also probably fixes #630
> Prevent crashing on invalid parameters

- CHANGELIST.md
- MPF.Core/Data/Drive.cs
If `S/STARTUP-SEQUENCE` is found, it's either CDTV or CD32
If `CDTV.TM` is found, it *must* be CDTV, but I'm told there exists CDTV discs without that file
This commit defaults to CD32 if it doesn't contain `CDTV.TM`
> Differentiate CD32 from CDTV

- CHANGELIST.md
- MPF.Core/InfoTool.cs
- MPF.Core/UI/ViewModels/DiscInformationViewModel.cs
Applies NormalizeDiscTitle to the main title field during SubmissionInfo generation.
Does not operate on Foreign Title as that field does not need alphabetization?
Implements the work done to fix #365 (I assume this is the desired output?)
Probably needs more testing
> Normalize Disc Title in Submission Info

- CHANGELIST.md
- MPF.Core/UI/ViewModels/CheckDumpViewModel.cs
- MPF.Core/UI/ViewModels/MainViewModel.cs
- MPF.UI.Core/Windows/CheckDumpWindow.xaml
- MPF.UI.Core/Windows/CheckDumpWindow.xaml.cs
- MPF.UI.Core/Windows/MainWindow.xaml
- MPF.UI.Core/Windows/MainWindow.xaml.cs
Creates a new window accessible via Tools -> Check Dump
The window acts as a GUI for MPF.Check functionality, allowing the main MPF UI program to provide an interface for creating submission info for dumps performed outside of MPF such as PSP and GC/Wii dumps.
The MPF.Check options follow whatever the main UI options are set as.
Protection scanning is currently not supported for the Check Dump GUI as you can run protection scanning via the main window.
Some naive checks are performed to disable the "Check Dump" button, and a message box will appear with an error message if MPF.Check failed. On success, the Disc Information Window will appear, followed by a message box asking if you wish to check another dump.
Example screenshot of the Check Dump GUI:
Fixes #466
> Add a GUI for MPF.Check

- CHANGELIST.md
- MPF.Core/InfoTool.cs
- MPF.Core/Modules/DiscImageCreator/Parameters.cs
- MPF.Core/Modules/Redumper/Parameters.cs
Parses EXE date from DIC and Redumper logs for PSX/PS2/KP2 discs if it exists, falling back to the previous method of MPF reading the date directly if it does not exist in the logs.
Using Redumper with MPF.Check will get the exe date, but DIC with MPF.Check won't because MPF needs to read the system.cnf file from the drive in order to parse exe date from DIC logs.
Fixes #626
> Parse PSX/PS2/KP2 exe date from logs

- CHANGELIST.md
- MPF.Core/SubmissionInfoTool.cs
Add cases for A.2 and AA.2
Extra cases or better logic can be added in future if needed.
Fixes #640
> Exclude extra tracks when finding disc matches

- CHANGELIST.md
- MPF.Core/Data/Options.cs
Sets the Redumper verbose flag by default.
Redumper logs will not look any different if no errors occuring during dumping.
> Verbose Redumper log by default

- CHANGELIST.md
- MPF/MPF.csproj
Compiler (even [Appveyor](https://ci.appveyor.com/project/mnadareski/mpf/builds/49110150)) currently gives this warning for .NET Core builds:
`warning MSB3243: No way to resolve conflict between "PresentationFramework.Aero2, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" and "PresentationFramework.Aero2". Choosing "PresentationFramework.Aero2, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" `
I'm unsure what is already implicitly pulling PresentationFramework.Aero2, but by removing the redundant reference, this warning goes away (check the [appveyor compiler messages for this build](https://ci.appveyor.com/project/mnadareski/mpf/builds/49123283)).
> Fix compiler warning

- CHANGELIST.md
- MPF.Core/Modules/DiscImageCreator/Parameters.cs
MPF currently parses 
> Version of challenge table: 02
in DIC logs as the SS (security sector) version.
This is actually DIC's way of saying the XGD version (1 = Xbox, 2 = Xbox360): https://github.com/saramibreak/DiscImageCreator/blob/31b4d32082a1ec00cf69e6edb369f982001ac807/DiscImageCreator/execScsiCmdforDVD.cpp#L1959
Instead, the SS version for all Kreon dumps using DIC is 1. Useful SSv2 data is only obtainable by 0800 drives, which are not supported by DIC (or any of MPF's current dumping programs).
> Fix DIC log parsing for SS version

- CHANGELIST.md
- MPF.Core/DumpEnvironment.cs
- MPF.Core/UI/ViewModels/MainViewModel.cs
If a dumping program has been deleted from the `Programs/` folder, or it was not bundled with an MPF build, remove it from the list of selectable dumping programs on the main window.
If no programs are found, warn the user.
This is an attempt at a soft solution for #527 whereby support for dumping with DIC remains intact, but at some point in the future, MPF releases can be packaged without bundled DIC, and users who wish to dump with DIC will just need to add it to the `Programs/` folder.
Perhaps something similar needs adding to the Default Dumping Program dropdown in the Options window, but for now it works fine if the default program is not available. Having a default program that doesn't exist (yet) could be a desired option anyway?
> Hide unavailable dumping programs

- CHANGELIST.md
- MPF.Core/Data/Options.cs
- MPF.Core/DumpEnvironment.cs
- MPF.Core/InfoTool.cs
- MPF.Core/UI/ViewModels/CreateIRDViewModel.cs
- MPF.Core/UI/ViewModels/MainViewModel.cs
- MPF.Core/UI/ViewModels/OptionsViewModel.cs
- MPF.Core/Utilities/Tools.cs
- MPF.UI.Core/Windows/OptionsWindow.xaml
Adds yet another checkbox in the Dumping options menu to create an IRD file following a PS3 BD-ROM dump.
This is not by default as it can take up to 10min for a large ISO on an HDD.
The IRD creation will occur following the disc information window, it is the last thing to happen after a PS3 dump. This ensures that if a user is not patient and force-closes MPF, then the logs for that dump have already been zipped, etc.
It will also ONLY occur if the Disc Key field was filled in on the Disc Information Window.
Pulling the key from redump is currently not implemented - perhaps this needs to occur by default if a match is found?
Fixes #323
> Opt-in automatic IRD creation after PS3 dump

- MPF.Core/Converters/EnumConverter.cs
- MPF.Core/Data/Enumerations.cs
- MPF.Core/DumpEnvironment.cs
- MPF.Core/Modules/PS3CFW/Parameters.cs
- MPF.Core/SubmissionInfoTool.cs
- MPF.Core/UI/ViewModels/CheckDumpViewModel.cs
- MPF.Core/Utilities/Tools.cs
Had a go at adding PS3 CFW support, which requires parsing .getkey.log, .disc.pic, ISO hash and ISO PVD.
Requires a bit more testing
> Add PS3 CFW support to MPF.Check

- CHANGELIST.md
- MPF.Core/Data/Options.cs
- MPF.Core/DumpEnvironment.cs
- MPF.Core/InfoTool.cs
- MPF.Core/MPF.Core.csproj
- MPF.Core/UI/ViewModels/CreateIRDViewModel.cs
- MPF.Core/UI/ViewModels/MainViewModel.cs
- MPF.Core/UI/ViewModels/OptionsViewModel.cs
- MPF.UI.Core/Windows/MainWindow.xaml
- MPF.UI.Core/Windows/OptionsWindow.xaml
No longer limited to .NET 6
However, IRDs created with frameworks prior to .NET 6 will not be byte-identical due to the different GZipStream compression level used. The contents should be the same though.
> Enable LibIRD for all .NET frameworks

- CHANGELIST.md
- MPF.Core/Utilities/OptionsLoader.cs
Allow OptionsLoader to read from the options even if they are currently being written to (primarily by Check UI and Create IRD windows).
This fixes rare crashes when the user is too fast at opening a new window immediately after changing the options.
> Fix config access permissions

- CHANGELIST.md
- MPF.Core/MPF.Core.csproj
pre-0.8.0 has a bug in generating certain IRDs, therefore requiring an update in MPF
> Update LibIRD to 0.8.0

- CHANGELIST.md
- MPF.Core/MPF.Core.csproj
Revisionist history
Fixes another breaking bug. Should be the last update to LibIRD until/unless ST.Compression gets GZipStream support.
> Update LibIRD to 0.9.0

- CHANGELIST.md
- MPF.Core/Modules/BaseParameters.cs
Assumes that first instance of `=` symbol in command part is the one delimiting the value
Fixes #686
> Fix parameter parsing for `=` symbol

- CHANGELIST.md
- MPF.Core/SubmissionInfoTool.cs
- Defines better default categories for some audio/video/multimedia systems.
- Also only overwrites fields when they're null, in case future MPF gets these values from logs, etc.
Fixes #688
> Define better default categories

- CHANGELIST.md
- MPF.Core/Converters/EnumConverter.cs
- MPF.Core/Data/Enumerations.cs
- MPF.Core/Data/Options.cs
- MPF.Core/Modules/Redumper/Parameters.cs
- MPF.Core/UI/ViewModels/OptionsViewModel.cs
- MPF.UI.Core/ElementConverter.cs
- MPF.UI.Core/Windows/OptionsWindow.xaml
- MPF.UI.Core/Windows/OptionsWindow.xaml.cs
Currently, MPF UI options allows for Redumper BE_CDDA mode and GENERIC drive type.
These are somewhat arbitrary (e.g. why not also allow BE mode, or other drive types) and more importantly can misinform users who may set these options without knowing that they are not supported for redump submission.
This PR gates GENERIC drive mode behind a new "Non-Redump Mode", as well as extends read method beyond just BE_CDDA, and adds a new sector order option (Fixes #690 )
Preview:
Checking non-redump options shows a warning:
The advanced Redumper options can now be set.
Unchecking Non-Redump Options resets the three options back to their defaults.
> Custom non-redump Redumper options

- CHANGELIST.md
- MPF.Core/Data/Options.cs
- MPF.Core/Modules/Redumper/Parameters.cs
- MPF.UI.Core/Windows/OptionsWindow.xaml
Adds a new textbox to set default plextor leadin retries, below the default reread option. Defaults to 4.
Fixes #692
> Option for default Redumper leadin retries

- CHANGELIST.md
- MPF.Core/Modules/CleanRip/Parameters.cs
MPF since #685 has not been pulling info from redump for CleanRip dumps.
ClrMameProData should always be generated by all modules, even if not CDROM.
#685 gated it incorrectly, the Disc Information Window knows how to deal with ClrMameProData and ISO hashes both being present.
> Fix CleanRip not pulling info

- CHANGELIST.md
- MPF.Core/SubmissionInfoTool.cs
XboxOne/XboxSX has a post-dump error since at least v3.1.6 due to a bug where SiteCode.Filename is not present in the dictionary during null-coalescing check
This fixes it
> Fix XboxOne/XboxSX Filename bug

- CHANGELIST.md
- MPF.Core/Modules/BaseParameters.cs
- MPF.Core/Modules/DiscImageCreator/Parameters.cs
- MPF.Core/Modules/Redumper/Parameters.cs
XboxOne/XboxSeriesX discs currently have their entire PIC printed in logs. This trims it similar to PS3/4/5 currently are.
I have decided not to add other systems because PC BD-ROMs are rare and BD-Video can be weird.
> Trim PIC for XboxOne/XboxSX

- CHANGELIST.md
- MPF.Core/Modules/Redumper/Parameters.cs
Currently, MPF requires the drive to be available to get PlayStation info such as internal serial and version.
This change parses PlayStation info from the redumper log first and foremost, falling back to the drive if the data is not available.
This will also be forward-compatible for any future redumper versions that support PS3/4/5 metadata.
> Prefer PlayStation info from Redumper logs

- CHANGELIST.md
- MPF.Frontend/ViewModels/MainViewModel.cs
Catch 22 with output name relying on new environment and new environment using output name.
Fixes #716
> Fix parameters after extension change

- MPF.Frontend/DumpEnvironment.cs
Changes, for example, `Writing information to !submissionInfo.txt...` to `Writing submission info file...`. This is because the filename may not actually be !submissionInfo.txt depending on options chosen. Follow-up to and alternative to #725.
> Change to generic wording in report

- MPF.Check/Program.cs
The --protect-file option itself was removed in e0482aad78d3fa4086ae2dba542ab05c7f0ed3d4 but was still referred to in the help text.
> Remove old --protect-file mentions

- MPF.Processors/UmdImageCreator.cs
Current WIP (not stable) isn't zipping the _drive log file from UmdImageCreator, this PR just adds it back to the list
> Add _drive.txt file to GetOutputFiles for UmdImageCreator

- CHANGELIST.md
- MPF.Frontend/Tools/SubmissionGenerator.cs
Whenever an entry that is in redump has the following occur:
`Multiple matches found for aa64beff052e53741bba9c2f10aa781d05c96e38`
i.e. multiple IDs are found for a track, MPF flags the dump as a non-fully-matching ID.
This fixes it.
> Fix fully matching when multiple matches found

- CHANGELIST.md
- MPF.Processors/ProcessingTool.cs
Currently copy-pasting the PIC from redump.org does not work as the parser only removes the \n character
This fixes it to remove both \n and \r
> Fix PIC parser

- CHANGELIST.md
- MPF.Processors/CleanRip.cs
Intended output:
```
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 5044 4D43 0905 8805 2000 2008
```
Adds a space after every 4 characters, except for every 32 characters where it replaces with a newline instead.
> Don't add trailing spaces to BCA output

- CHANGELIST.md
- MPF.Processors.Test/DiscImageCreatorTests.cs
- MPF.Processors.Test/RedumperTests.cs
- MPF.Processors.Test/TestData/Redumper/CDROM/test.log
- MPF.Processors/DiscImageCreator.cs
- MPF.Processors/Redumper.cs
An attempt to solve #714
Needs testing before merging.
> Add DumpingParameters for DIC and Redumper

- CHANGELIST.md
- MPF.Frontend/Tools/SubmissionGenerator.cs
If all labels are deleted, revert to using just the drive label, re: https://github.com/SabreTools/MPF/issues/744
> Fix bug with volume labels

- CHANGELIST.md
- MPF.Processors/Redumper.cs
Checks whether a DMI has data in it before requiring a .security file from Redumper dumps
Fixes #774
> Enable handling non-SS Xbox discs

- CHANGELIST.md
- MPF.Processors/Redumper.cs
Fixes an issue with MPF not finding the manufacturer file during output file check
Also minor refactor of IsManufacturerEmpty routine
> Use proper base path for redumper output check

- CHANGELIST.md
- MPF.Frontend/Tools/PhysicalTool.cs
- MPF.Frontend/Tools/SubmissionGenerator.cs
For PS4 and PS5 discs, puts app.pkg Content ID and pkg Date into the Contents field, with SiteCode.Games 
PS4 Example:
```
<b>Games</b>:
app.pkg ID: EP4365-CUSA17823_00-SPACE00STARTOPIA
app.pkg Date: 2019-08-01
```
PS5 Example:
```
<b>Games</b>:
app_sc.pkg ID: UP2125-PPSA03355_00-3466019145463410
app_sc.pkg Date: 2020-07-22
```
Tested.
Solves #771
> Print PS4/PS5 app.pkg info

- CHANGELIST.md
- MPF.Frontend/Tools/PhysicalTool.cs
- MPF.Frontend/ViewModels/MainViewModel.cs
- Reads the Sega Header to detect the system
- Better PS5 detection
- FMT detection
- Amiga CD (non-CD32/CDTV)
- 3DO detection (no false positives, but won't detect all 3DO discs)
- Neo Geo CD detection
- NUON detection
- GameWave detection
- VIS detection
- If PC is default and disc has unreadable filesystem, default to Mac instead
> Improve system detection

- MPF.UI/Windows/DiscInformationWindow.xaml.cs
Comments and Contents fields in redump don't like tab characters, so those fields in the Disc Information Window don't need tab input.
This should minimize complaints about tab navigation not being default, as it will only occur on the Ringcode tab (where it is the most important).
> Tab input only needed for ringcodes

- CHANGELIST.md
- MPF.Processors.Test/PS3CFWTests.cs
- MPF.Processors/PS3CFW.cs
Add pure getkey output names for PS3CFW (getkey.log, disc.pic)
Also, zip any CUE file generated by multiman
> Add pure-getkey output names for PS3CFW

- CHANGELIST.md
- MPF.Frontend/Tools/PhysicalTool.cs
- MPF.Frontend/ViewModels/MainViewModel.cs
- MPF.UI/External/WPFCustomMessageBox/CustomMessageBoxWindow.xaml
- MPF.UI/UserControls/UserInput.xaml
- MPF.UI/Windows/DiscInformationWindow.xaml
- MPF.UI/Windows/OptionsWindow.xaml
- MPF.UI/Windows/RingCodeGuideWindow.xaml
- Increase width of Disc Information Window
- Change ratio of UserInput fields (3:5 to 3:6)
- Don't log drive speed change when scan for discs is pressed
- Add rounded corners to custom message box
- Standardize top margin of windows
- Better deal with case when SYSTEM.CNF doesn't exist in PSX discs
- Don't print VersionHash field for PS4/PS5 app.pkg data
> Minor UI and other fixes

- MPF.Frontend/ViewModels/MainViewModel.cs
- MPF.UI/UserControls/UserInput.xaml
- MPF.UI/Windows/DiscInformationWindow.xaml
- publish-nix.sh
- Add group boxes to Contents and Read-only info tabs
- Change userinput ratio from 3:6 to 3:7
- Add better examples to debug DIW
> Minor UI changes to DIW

- CHANGELIST.md
- MPF.Frontend/Tools/PhysicalTool.cs
Fixes two pkgs printing on the same line
http://forum.redump.org/post/126658/
> Add newlines to pkg info printing

- CHANGELIST.md
- MPF.Processors/PS3CFW.cs
- MPF.Processors/XboxBackupCreator.cs
This fixes a design error where PS3CFW expects output files with consistent basename, while ManaGunZ has filestamps in the default output name (unique per file).
I also added a literal period to the XBC log.txt check (is this needed?)
> Relax PS3CFW output filename requirements

- CHANGELIST.md
- MPF.Processors.Test/RedumperTests.cs
- MPF.Processors/Redumper.cs
For multisession CDs, .cache file is split into .1.cache and .2.cache
DVDs also never generate .asus or .cache
> redumper multisession .cache

- MPF.Frontend/Tools/ProtectionTool.cs
Removes things that are either unnecessary for the redump protection field, or outright should not be included in it.
> Add filters to handle Release Control output.

- CHANGELIST.md
- MPF.Frontend/Options.cs
- MPF.Frontend/ViewModels/MainViewModel.cs
- MPF.UI/Windows/OptionsWindow.xaml
`SkipMediaTypeDetection` option is now mostly obsolete, so this PR removes it.
Unlike long ago, MPF no longer uses the old third party library (no chance of freezing the UI so there is no essential need for the option).
And as of recently, only DIC execution context cares about the media type, so I have replaced the option with a check against Internal Program. Media type detection now runs only when DIC is selected.
Additionally, a couple of minor UI fixes have been made in the Options window.
> Remove SkipMediaTypeDetection option, cleanup options window
